name = "dytsou-site-edge"
main = "src/index.ts"
compatibility_date = "2025-06-01"
account_id = "c457ded6af8937c1aa9032b5396f2f05"

[observability]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1

[vars]
ORIGIN_BASE = "https://raw.githubusercontent.com/dytsou/dytsou.github.io/main/"

[[routes]]
pattern = "dy.tsou.me/*"
zone_name = "tsou.me"
