name = "dytsou-site-edge"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[vars]
ORIGIN_BASE = "https://raw.githubusercontent.com/dytsou/dytsou.github.io/main/"

[[routes]]
pattern = "dy.tsou.me/*"
zone_name = "tsou.me"
