import type { Project } from '../../types/projects';

export const PROJECTS_CONTENTS: Project[] = [
  {
    id: 'kore-ji/koreji-frontend',
    title: 'Koreji',
    description: '',
    technologies: [],
    tags: ['time-management', 'productivity', 'mobile-app'],
    github_url: 'https://github.com/kore-ji/koreji-frontend',
    featured: true,
  },
  {
    id: 'NYCU-SDC/core-system-backend',
    title: 'SDC Core System',
    description:
      'Backend infrastructure for NYCU Software Development Club. Built a robust RESTful API system with Go, featuring Docker containerization and PostgreSQL database management.',
    technologies: [],
    tags: ['erp', 'golang-system', 'rest-api', 'docker', 'postgresql'],
    github_url: 'https://github.com/NYCU-SDC/core-system-backend',
    featured: true,
  },
  {
    id: 'dytsou/NextMeeting',
    title: 'NextMeeting',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/NextMeeting',
    featured: true,
  },
  {
    id: 'MCHackathon2025/CAIender-frontend',
    title: 'CAIender',
    description: '',
    technologies: [],
    tags: ['ai', 'helper', 'hackathon'],
    github_url: 'https://github.com/MCHackathon2025/CAIender-frontend',
    featured: true,
  },
  {
    id: 'dytsou/shorten-url',
    title: 'Shorten URL',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/shorten-url',
    featured: false,
  },
  {
    id: 'dytsou/github-readme-stats',
    title: 'GitHub README Stats',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/github-readme-stats',
    featured: true,
  },
  {
    id: 'dytsou/raycast-rsync-extension',
    title: 'Raycast Rsync Extension',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/raycast-rsync-extension',
    featured: false,
  },
  {
    id: 'dytsou/Dungeon',
    title: 'Dungeon',
    description: '',
    technologies: [],
    tags: ['dungeons-and-dragons', 'text-based', 'game'],
    github_url: 'https://github.com/dytsou/Dungeon',
    featured: false,
  },
  {
    id: 'dytsou/resume',
    title: 'Resume Builder',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/resume',
    featured: false,
  },
  {
    id: 'dytsou/intern-corner-scheduler',
    title: 'Intern Corner Scheduler',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/intern-corner-scheduler',
    featured: false,
  },
  {
    id: 'dytsou/GenAI-Studio',
    title: 'GenAI Studio',
    description: '',
    technologies: [],
    tags: [],
    github_url: 'https://github.com/dytsou/GenAI-Studio',
    featured: false,
  },
] as Project[];
